# Generated by Django 3.2 on 2025-03-25 12:09

from django.db import migrations, models

import api.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20250323_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[api.common.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
